--QLBH
--11. Ngày mua hàng (NGHD) của một khách hàng thành viên sẽ lớn hơn hoặc bằng ngày 
--khách hàng đó đăng ký thành viên (NGDK). 
CREATE TRIGGER TRG_AFTER_CHECK
ON KHACHHANG
AFTER UPDATE
AS
BEGIN 
DECLARE @NGDK SMALLDATETIME
SELECT @NGDK = NGDK FROM INSERTED
IF @NGDK >ANY( SELECT HD.NGHD
				FROM HOADON HD JOIN INSERTED ON  HD.MAKH= INSERTED.MAKH
				)
	BEGIN 
	 RAISERROR ( 'NGAY DANG KY PHAI NHO HON NGAY MUA HANG', 16,1)
	 ROLLBACK TRANSACTION
	 END
	 ELSE PRINT N'CẬP NHẬT THÀNH CÔNG'
END;
GO			
CREATE TRIGGER TRG_CHECK_NGHD_HOADON
ON HOADON
AFTER INSERT, UPDATE
AS
BEGIN
 DECLARE @NGHD SMALLDATETIME, @NGDK SMALLDATETIME
 SELECT @NGHD = NGHD, @NGDK=NGDK FROM INSERTED JOIN KHACHHANG KH ON KH.MAKH =INSERTED.MAKH
 IF( @NGHD < @NGDK) 
 BEGIN
  PRINT('NGAY HOA DON KHONG DUOC NHO HON NGAY DANG KY THANH VIEN')
  ROLLBACK TRANSACTION
  END
  ELSE
  BEGIN
  PRINT('CAP NHAT THANH CONG')
  END
  END;


              


--12. Ngày bán hàng (NGHD) của một nhân viên phải lớn hơn hoặc bằng ngày nhân viên đó 
--vào làm. 
GO
CREATE TRIGGER TRG_CHECK_NGVL
ON NHANVIEN
AFTER UPDATE
AS
BEGIN
DECLARE @NGVL SMALLDATETIME
SELECT @NGVL = NGVL FROM INSERTED
IF @NGVL >ANY( SELECT HD.NGHD 
				FROM HOADON HD JOIN INSERTED ON  HD.MANV =INSERTED.MANV)
		BEGIN
		RAISERROR('NGAY VAO LAM PHAI NHO HON HOAC BANG NGAY BAN HANG',16,1)
		ROLLBACK TRANSACTION
		END
		ELSE 
		PRINT N'CẬP NHẬT THÀNH CÔNG'
END;

--QUANLYGIAOVU
GO
USE QUANLIGIAOVU_0208
--9.Lớp trưởng của một lớp phải là học viên của lớp đó. 
GO
CREATE TRIGGER TRG_CHECK_LOPTRG
ON LOP
AFTER UPDATE, INSERT
AS 
BEGIN
DECLARE @TRGLOP CHAR(5), @MALOP CHAR(3)
 SELECT @TRGLOP=TRGLOP, @MALOP= MALOP FROM INSERTED
 IF EXISTS (SELECT * FROM HOCVIEN HV WHERE MALOP= @MALOP AND MAHV=@TRGLOP) 
  BEGIN
   PRINT('LOP TRUONG LA HOC VIEN CUA LOP')
   END 
   ELSE
   BEGIN 
   RAISERROR(' LOP TRUONG KHONG PHAI HOC VIEN CUA LOP',16,1)
   ROLLBACK TRANSACTION
   END
END;
GO
CREATE TRIGGER TRG_DEL_HOCVIEN
ON HOCVIEN
AFTER DELETE
AS 
BEGIN
IF EXISTS (SELECT * FROM DELETED D JOIN LOP L ON D.MAHV=L.TRGLOP	
						WHERE D.MALOP=L.MALOP)
 BEGIN 
	 RAISERROR ('HOC VIEN HIEN TAI DANG LA LOP TRUONG',16,1)
	 ROLLBACK TRANSACTION
	 END 
	 ELSE
	 BEGIN
	 PRINT('DA XOA')
	 END
END;

--TEST
SELECT * FROM LOP
DELETE FROM LOP WHERE MALOP='K14'
INSERT INTO LOP VALUES ('K14','LOP 1 KHOA 2', 'K1114','11','GV07') 

--10. Trưởng khoa phải là giáo viên thuộc khoa và có học vị “TS” hoặc “PTS”. 

GO
CREATE TRIGGER TRG_CHECK_TRGKHOA
ON KHOA
AFTER UPDATE,INSERT
AS 
BEGIN 
DECLARE @TRGKHOA CHAR(4), @MAKHOA VARCHAR(4)
SELECT @TRGKHOA= TRGKHOA, @MAKHOA= MAKHOA FROM KHOA
IF EXISTS( SELECT * FROM GIAOVIEN WHERE HOCVI='TS'OR HOCVI='PGS'AND MAGV=@TRGKHOA AND MAKHOA = @MAKHOA )
  BEGIN 
  PRINT ' GIAO VIEN THUOC KHOA'
  END
  ELSE 
  BEGIN
  RAISERROR ('GIANG VIEN KHONG THUOC KHOA',16,1)
  ROLLBACK TRANSACTION
  END
END;


--15. Học viên chỉ được thi một môn học nào đó khi lớp của học viên đã học xong môn học này. 
GO
CREATE TRIGGER TRG_CHECK_HOCVIEN_THI
ON HOCVIEN
AFTER INSERT, UPDATE
AS
BEGIN
    IF (
        SELECT COUNT(*)
        FROM inserted i
        JOIN KETQUATHI kq ON i.MAHV = kq.MAHV
        JOIN GIANGDAY gd1 ON i.MALOP = gd1.MALOP AND kq.MAMH = gd1.MAMH
        WHERE 
            kq.MAMH NOT IN (
                SELECT gd2.MAMH
                FROM GIANGDAY gd2
                WHERE gd2.MALOP = i.MALOP
            )
            OR kq.NGTHI > gd1.DENNGAY
    ) > 0
    BEGIN
        ROLLBACK TRANSACTION
        PRINT N'Cập nhật không thành công'
    END
    ELSE
    BEGIN
        PRINT N'Cập nhật thành công'
    END
END
GO

--16. Mỗi học kỳ của một năm học, một lớp chỉ được học tối đa 3 môn. 
CREATE TRIGGER TRG_CHECK_MON
ON GIANGDAY
AFTER INSERT, UPDATE
AS
BEGIN
	IF( SELECT COUNT(*)
		FROM INSERTED I JOIN GIANGDAY G  ON I.MALOP=G.MALOP
		WHERE I.HOCKY= G.HOCKY) >3
	BEGIN
		RAISERROR ('LOI: MOT LOP KHONG DUOC HOC QUA 3 MON', 16, 1)
		ROLLBACK TRANSACTION
	END
END
GO

--17. Sỉ số của một lớp bằng với số lượng học viên thuộc lớp đó. 
CREATE TRIGGER TRG_CHECK_SI_SO
ON LOP
AFTER INSERT
AS
BEGIN
	IF EXISTS ( SELECT *
		FROM INSERTED I JOIN (SELECT MALOP, COUNT(*) SL FROM HOCVIEN GROUP BY MALOP) H
		ON I.MALOP=H.MALOP
		WHERE I.SISO <> H.SL )
	BEGIN
		RAISERROR ('LOI: SI SO LOP PHAI BANG SL HOCVIEN', 16, 1)
		ROLLBACK TRANSACTION
	END
END
GO
--18. Trong quan hệ DIEUKIEN giá trị của thuộc tính MAMH và MAMH_TRUOC trong cùng một bộ 
--không được giống nhau (“A”,”A”) và cũng không tồn tại hai bộ (“A”,”B”) và (“B”,”A”). 

CREATE TRIGGER TRG_CHECK_DIEU_KIEN
ON DIEUKIEN
AFTER INSERT, UPDATE
AS
BEGIN
	IF EXISTS( SELECT *
		FROM INSERTED I
		WHERE I.MAMH=I.MAMH_TRUOC)
	BEGIN
		RAISERROR('LOI: 2 THUOC TINH TRONG CUNG 1 BO KHONG DUOC GIONG NHAU', 16, 1)
		ROLLBACK TRAN
	END

	IF EXISTS ( SELECT *
		FROM INSERTED I, DIEUKIEN D
		WHERE (I.MAMH=D.MAMH AND I.MAMH_TRUOC=D.MAMH_TRUOC)
		OR (I.MAMH=D.MAMH_TRUOC AND I.MAMH_TRUOC=D.MAMH))
	BEGIN
		RAISERROR('LOI: KHONG DUOC TON TAI 2 BO GIA TRI GIONG NHAU HOAC DOI XUNG NHAU', 16, 1)
		ROLLBACK TRANSACTION
	END
END
GO
--19. Các giáo viên có cùng học vị, học hàm, hệ số lương thì mức lương bằng nhau. 

CREATE TRIGGER TRG_CHECK_LUONG
ON GIAOVIEN
AFTER INSERT, UPDATE
AS
BEGIN
	IF EXISTS ( SELECT *
		FROM INSERTED I JOIN GIAOVIEN G ON I.MAGV=G.MAGV AND I.HOCVI= G.HOCVI AND I.HOCHAM=G.HOCHAM
		WHERE  I.HESO =G.HESO AND I.MUCLUONG <> G.MUCLUONG)
	BEGIN
		RAISERROR ('LOI: CAC GIAO VIEN CO CUNG HOCVI, HOCHAM, HESO THI PHAI CO CUNG MUC LUONG', 16, 1)
		ROLLBACK TRANSACTION
	END
END
GO
--20. Học viên chỉ được thi lại (lần thi >1) khi điểm của lần thi trước đó dưới 5. 
CREATE TRIGGER TRG_CHECK_THI_LAI
ON KETQUATHI
AFTER INSERT, UPDATE
AS
BEGIN
	IF EXISTS ( SELECT *
		FROM KETQUATHI K, INSERTED I
		 WHERE I.MAHV=K.MAHV AND K.MAMH=I.MAMH 
		AND I.LANTHI >1 AND I.LANTHI = K.LANTHI +1 AND K.DIEM >= 5)
	BEGIN
		RAISERROR ('KHONG DU DIEU KIEN THI NUA',16, 1)
		ROLLBACK TRANSACTION
	END
END
GO

--21. Ngày thi của lần thi sau phải lớn hơn ngày thi của lần thi trước (cùng học viên, cùng môn học). 

CREATE TRIGGER TRG_CHECK_LAN_THI
ON KETQUATHI
AFTER INSERT, UPDATE
AS
BEGIN
	IF EXISTS ( SELECT *
		FROM INSERTED I, KETQUATHI K
		WHERE I.MAHV =K.MAHV AND I.MAMH= K.MAMH AND I.LANTHI= K.LANTHI + 1 AND I.NGTHI <= K.NGTHI)
	BEGIN
		RAISERROR('LOI: NGTHI CUA LAN THI SAU PHAI LON HON CUA LANTHI TRUOC', 16, 1)
		ROLLBACK TRANSACTION
	END
END
GO
--22. Học viên chỉ được thi những môn mà lớp của học viên đó đã học xong. 

CREATE TRIGGER TRG_CHECK_HOCVIEN_THI
ON HOCVIEN
AFTER INSERT, UPDATE
AS
BEGIN
    IF (
        SELECT COUNT(*)
        FROM inserted i
        JOIN KETQUATHI kq ON i.MAHV = kq.MAHV
        JOIN GIANGDAY gd1 ON i.MALOP = gd1.MALOP AND kq.MAMH = gd1.MAMH
        WHERE 
            kq.MAMH NOT IN (
                SELECT gd2.MAMH
                FROM GIANGDAY gd2
                WHERE gd2.MALOP = i.MALOP
            )
            OR kq.NGTHI > gd1.DENNGAY
    ) > 0
    BEGIN
        ROLLBACK TRANSACTION
        PRINT N'Cập nhật không thành công'
    END
    ELSE
    BEGIN
        PRINT N'Cập nhật thành công'
    END
END
GO

--23. Khi phân công giảng dạy một môn học, phải xét đến thứ tự trước sau giữa các môn học (sau khi học 
--xong những môn học phải học trước mới được học những môn liền sau). 

CREATE TRIGGER TRG_CHECK_PHAN_CONG
ON GIANGDAY
AFTER INSERT, UPDATE
AS
BEGIN
	IF EXISTS ( SELECT *
		FROM INSERTED I, DIEUKIEN D, GIANGDAY G
		WHERE I.MAMH= D.MAMH AND D.MAMH_TRUOC = G.MAMH AND I.MALOP=G.MALOP AND G.DENNGAY >= I.TUNGAY)
	BEGIN
		RAISERROR(' LOI: MON HOC TRUOC CHUA HOAN THANH TRUOC MON HOC SAU', 16,1)
		ROLLBACK TRANSACTION
	END
END

GO
--24. Giáo viên chỉ được phân công dạy những môn thuộc khoa giáo viên đó phụ trách. 
CREATE TRIGGER TRG_CHECK_PC_GIANGDAY
ON GIANGDAY
AFTER INSERT, UPDATE
AS
BEGIN
	IF NOT EXISTS ( SELECT *
		FROM INSERTED I, MONHOC M, GIAOVIEN G
		WHERE I.MAGV=G.MAGV AND I.MAMH=M.MAMH AND G.MAKHOA=M.MAKHOA)
	BEGIN
		RAISERROR('LOI: GIAO VIEN CHI DUOC DAY NHUNG MON THUOC KHOA PHU TRACH', 16,1 )
		ROLLBACK TRANSACTION
	END
END

