CREATE DATABASE THUCHANH
USE THUCHANH
CREATE TABLE SACH
( MASACH CHAR(5) PRIMARY KEY,
 TENSACH VARCHAR(100) ,
 THELOAI VARCHAR(30),
 DONGIA MONEY,
 SOLUONG INT,

)
SET DATEFORMAT DMY
CREATE TABLE TACGIA
( MATG CHAR(5) PRIMARY KEY,
  HOTEN VARCHAR(50),
  QUOCTICH VARCHAR(30),
  NGAYSINH SMALLDATETIME,
  DIENTHOAI VARCHAR(50),

)
CREATE TABLE TACGIA_SACH
( MATG CHAR(5) ,
  MASACH CHAR(5),
  	constraint pk_TACGIA_SACH primary key(MATG,MASACH)
  )
CREATE TABLE DOCGIA
( MADG CHAR(5) PRIMARY KEY,
  TENDG VARCHAR(50), 
  DIACHI VARCHAR(50),
  NGAYSINH SMALLDATETIME,
  DIENTHOAI VARCHAR(15),
  NGDK SMALLDATETIME,
 )
 CREATE TABLE PHATHANH
 ( MAPH CHAR(5) PRIMARY KEY,
    MASACH CHAR(5),
	NGAYPH SMALLDATETIME,
	SOLUONG INT,
	NXB VARCHAR(100),
	LANPHATHANH INT 
	)

  CREATE TABLE MUONSACH
  (
   MAMUON CHAR(5) PRIMARY KEY,
   MADG CHAR(5) ,
   MASACH CHAR(5),
   NGAYMUON SMALLDATETIME,
   NGAYTRA SMALLDATETIME,
   TRANGTHAI VARCHAR(20),
   )

ALTER TABLE TACGIA_SACH ADD CONSTRAINT FK01_TACGIA FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)

ALTER TABLE TACGIA_SACH ADD CONSTRAINT FK02_TACGIA FOREIGN KEY (MATG) REFERENCES TACGIA(MATG)
ALTER TABLE PHATHANH ADD CONSTRAINT FK_PH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
ALTER TABLE MUONSACH ADD CONSTRAINT FK01_MS FOREIGN KEY ( MADG ) REFERENCES DOCGIA( MADG)
ALTER TABLE MUONSACH ADD CONSTRAINT FK02_MS FOREIGN KEY ( MASACH) REFERENCES SACH(MASACH)
-- CAU 2
GO
CREATE TRIGGER TRG_CHECK_NGPH
ON PHATHANH
AFTER INSERT,UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM INSERTED I
        JOIN TACGIA_SACH TS ON I.MASACH = TS.MASACH
        JOIN TACGIA T ON TS.MATG = T.MATG
        WHERE I.NGAYPH <= T.NGAYSINH
    )
    BEGIN
        RAISERROR('NGAY PHAT HANH PHAI LON HON NGAY SINH TAC GIA', 16, 1);
        ROLLBACK TRANSACTION;
  END
END
GO

--CAU3

--A
CREATE TRIGGER TRG_CHECK_NGSINH_DG
ON DOCGIA
AFTER INSERT, UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM INSERTED I
        WHERE NGAYSINH >= NGDK
    )
    BEGIN
        RAISERROR( 'NGAY SINH PHAI NHO NGAY DK CUA DOC GIA', 16, 1);
        ROLLBACK TRANSACTION;
    END
END

GO

--B
CREATE TRIGGER TRG_CHECK_TTMUONSACH
ON MUONSACH
AFTER INSERT, UPDATE
AS
BEGIN 
     IF EXISTS 
	          ( SELECT 1 
			    FROM INSERTED I
				WHERE TRANGTHAI NOT IN ('Da Tra', 'Chua Tra')
				)
      BEGIN 
	  RAISERROR(' TRANG THAI CHI CO THE LA DA TRA HOAC CHUA TRA',16,1);
	  ROLLBACK TRANSACTION
	  END;
END

GO

--CAU 4
SELECT PH.NXB
FROM PHATHANH PH
WHERE PH.MASACH NOT IN 
  (
    SELECT MASACH FROM MUONSACH )

GROUP BY PH.NXB
HAVING COUNT(DISTINCT PH.MASACH) > 5;

--CAU 5
SELECT DG.MADG, DG.TENDG, S.MASACH, TENSACH
FROM MUONSACH MS JOIN DOCGIA DG ON DG.MADG = MS.MADG
                 JOIN SACH S ON S.MASACH= MS.MASACH
    
WHERE  YEAR(DG.NGAYSINH)=1990 AND MONTH(NGAYMUON)= 12 AND YEAR(NGAYMUON)=2024
--CAU 6

SELECT TG.MATG, TG.HOTEN, COUNT(TGS.MASACH)
FROM TACGIA_SACH  TGS JOIN TACGIA TG ON TGS.MATG= TG.MATG
                       JOIN PHATHANH PH ON TGS.MASACH= PH.MASACH

WHERE YEAR( NGAYPH)>2023 AND YEAR(NGAYPH)<2024  
GROUP BY TG.MATG, TG.HOTEN
ORDER BY COUNT(TGS.MASACH) ASC


--CAU 7
SELECT S.MASACH , S.TENSACH
FROM     TACGIA_SACH TGS  JOIN SACH S ON S.MASACH =TGS.MASACH
                          JOIN TACGIA TG ON TG.MATG= TGS.MATG
WHERE TG.HOTEN = 'DO PHUC' AND S.THELOAI NOT IN ('KY NANG SONG')
  INTERSECT

  SELECT S.MASACH , S.TENSACH
FROM     TACGIA_SACH TGS  JOIN SACH S ON S.MASACH =TGS.MASACH
                          JOIN TACGIA TG ON TG.MATG= TGS.MATG
WHERE TG.HOTEN = 'DO DUY THANH' AND S.THELOAI NOT IN ('KY NANG SONG')


-- CAU 8
SELECT * 
 FROM DOCGIA DG
WHERE NOT EXISTS 
                ( SELECT * 
				
				   FROM SACH S
				  WHERE NOT EXISTS 
				  ( SELECT * FROM MUONSACH MS 
				    WHERE  MS.MASACH =S.MASACH AND MS.MADG = DG.MADG))


